### ISSUE TITLE
validation test files

### ISSUE THREAD

**Issue by eLRuLL** [ChangUk/pyCollaborativeFiltering#1]
could you share your `u1.base` and `u1.test` files please?

**Comment by ChangUk** [comment]
Due to the constraints of file extensions, I appended ".txt" for each file name. You may be able to get other files (u2-u5) at the MovieLens official website.
[u1.base.txt](https://github.com/ChangUk/pyCollaborativeFiltering/files/4665/u1.base.txt)
[u1.test.txt](https://github.com/ChangUk/pyCollaborativeFiltering/files/4666/u1.test.txt)

**Comment by eLRuLL** [comment]
nice, thanks.
